// <auto-generated />
using System;
using CQRSAndSpecificationWithRepository.Infrastructure.DataHelper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CQRSAndSpecificationWithRepository.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "mohamed@example.com",
                            Name = "Mohamed Kamal",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "ahmed@example.com",
                            Name = "Ahmed Ali",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "sara@example.com",
                            Name = "Sara Ibrahim",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "omar@example.com",
                            Name = "Omar Hassan",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 4,
                            Email = "fatima@example.com",
                            Name = "Fatima Adel",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "kareem@example.com",
                            Name = "Kareem Saad",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Email = "laila@example.com",
                            Name = "Laila Noor",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Email = "ayman@example.com",
                            Name = "Ayman Reda"
                        });
                });

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ERP System"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HR Management"
                        },
                        new
                        {
                            Id = 3,
                            Name = "E-Commerce Platform"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Financial Forecasting Tool"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Marketing Campaign Automation"
                        });
                });

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Employee", b =>
                {
                    b.HasOne("CQRSAndSpecificationWithRepository.Domain.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CQRSAndSpecificationWithRepository.Domain.Models.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CQRSAndSpecificationWithRepository.Domain.Models.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
